apiVersion: v1
kind: PersistentVolume
metadata:
  name: f1-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/edward/Workspace/mysql/f1-db-mount"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f1-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
